# Generated by Django 4.0.4 on 2022-05-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentImage',
        ),
    ]
