# Generated by Django 4.0.4 on 2022-05-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_alter_attendence_std_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
    ]
