# Generated by Django 4.0.4 on 2022-05-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_address_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
