# Generated by Django 4.0.4 on 2022-05-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_std_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
